export const config = {
    RPC_URL: 'https://rpc.juno.omniflix.co',
    REST_URL: 'https://api.juno.omniflix.co',
    EXPLORER_URL: 'https://www.mintscan.io/juno',
    NETWORK_NAME: 'Juno',
    NETWORK_TYPE: 'mainnet',
    CHAIN_ID: 'juno-1',
    CHAIN_NAME: 'Juno',
    COIN_DENOM: 'JUNO',
    COIN_MINIMAL_DENOM: 'ujuno',
    COIN_DECIMALS: 6,
    PREFIX: 'juno',
    COIN_TYPE: 118,
    DEFAULT_GAS: 250000,
    GAS_PRICE_STEP_LOW: 0.005,
    GAS_PRICE_STEP_AVERAGE: 0.025,
    GAS_PRICE_STEP_HIGH: 0.08,
};
